name: Deploy to Azure VM

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json

    - name: Install backend dependencies
      run: |
        cd backend
        npm ci --production

    - name: Install frontend dependencies and build
      run: |
        cd frontend
        npm ci
        npm run build
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"

    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r backend/ deployment/
        cp -r frontend/build/ deployment/frontend-build/
        tar -czf deployment.tar.gz deployment/
        echo "Deployment package created at $(date)" >> deploy.log

    - name: Deploy to Azure VM
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        source: "deployment.tar.gz,deploy.log"
        target: "/home/${{ secrets.AZURE_VM_USERNAME }}/deployments/"

    - name: Execute deployment commands on VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          cd /home/${{ secrets.AZURE_VM_USERNAME }}/deployments/
          tar -xzf deployment.tar.gz
          
          # Deploy backend
          cd deployment/backend
          npm install --production
          pm2 delete retail-backend || true
          pm2 start server.js --name retail-backend
          pm2 save
          
          # Deploy frontend
          sudo rm -rf /home/azureuser/frontend-build
          sudo mv ../frontend-build /home/azureuser/
          sudo chown -R www-data:www-data /home/azureuser/frontend-build
          sudo chmod -R 755 /home/azureuser/frontend-build
          
          # Restart NGINX
          sudo systemctl restart nginx
          
          # Log deployment
          echo "Deployment completed successfully at $(date)" >> /home/azureuser/deployments/deploy.log

    - name: Verify deployment
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          echo "=== Backend Status ===" >> /home/azureuser/deployments/deploy.log
          pm2 status >> /home/azureuser/deployments/deploy.log
          echo "=== NGINX Status ===" >> /home/azureuser/deployments/deploy.log
          systemctl status nginx >> /home/azureuser/deployments/deploy.log
          echo "=== Test API ===" >> /home/azureuser/deployments/deploy.log
          curl -s http://localhost:5000/api/message >> /home/azureuser/deployments/deploy.log

    - name: Download deployment log
      uses: actions/download-artifact@v3
      with:
        name: deployment-log
        path: deployment-logs

    - name: Upload deployment log as artifact
      uses: actions/upload-artifact@v3
      with:
        name: deploy.log
        path: deployment-logs/deploy.log
